### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by schneidmaster** [Guidebook/sublime-cjsx#6]
Hi there -- just wondering if this project is still active. I still use Sublime + CoffeeScript and would like to make some tweaks (e.g. syntax highlighting for ES6-style imports/exports) -- looks like this repo has been idle for a while but I figured I'd check before forking.

**Comment by cooncesean** [comment]
@schneidmaster we haven't touched it since 2015, but I will make sure that whatever you want to merge into master gets reviewed and merged.

If you do open a PR, would you mind adding:

* What: Briefly describe the proposed changes.
* Why: The motivation behind the changes (reference this ticket).
* Testing: Instructions that allow another contributor to pull down your changes and test them out. If you have [licecap](http://www.cockos.com/licecap/), maybe include an animated gif of your changes in action.
